### ISSUE TITLE
Can't find the azure/azapi provider over the registry-ui

### ISSUE THREAD

**Issue by TeaAlc** [opentofu/registry-ui#123]
It seems that the provider azure/azapi can not be found:

```
terraform {
  required_version = ">= 1.7"
  required_providers {
      azapi = {
      source  = "azure/azapi"
      version = "1.15.0"
    }
  }
}

```

**Source Definition:** https://github.com/opentofu/registry/blob/main/providers/a/azure/azapi.json

---
The file defined in the source definition is downloadable via browser. (https://github.com/azure/terraform-provider-azapi/releases/download/v1.15.0/terraform-provider-azapi_1.15.0_darwin_amd64.zip)
It is also downloaded by OpenTofu:
```
- Installing azure/azapi v1.15.0...
- Installed azure/azapi v1.15.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```
...
```
$ tf providers | grep -i azapi
├── provider[registry.opentofu.org/azure/azapi] 1.15.0
    └── provider[registry.opentofu.org/azure/azapi] 1.15.0
```

**Comment by Yantrio** [comment]
Hi, We have not currently indexed this data right now. We have only indexed a subset of data for our initial testing. I can add this to our list :)

**Comment by TeaAlc** [comment]
Hi Yantrio big thx, that was fast :) 

Works fine: https://search.opentofu.org/provider/azure/azapi/latest
