### ISSUE TITLE
Unexpected error when opening results

### ISSUE THREAD

**Issue by mkesper** [opentofu/registry-ui#193]
### URL of the page that's broken

Results seem to be found but cannot be opened, e.g.:
https://search.opentofu.org/provider/hashicorp/aws/latest

### Screenshot

![Screenshot_20240906_145333](https://github.com/user-attachments/assets/d5276020-5c24-410f-9a2e-480dbf790547)
![Screenshot_20240906_145714](https://github.com/user-attachments/assets/aac57cd0-30ee-47b7-bb82-293318171e8d)

### OS, browser version, installed extensions

Debian GNU/Linux 12, Firefox 115.15.0esr (64-Bit), uBlock Origin, Privacy Badger,...

### Additional information

Browser console output:
Speicherzugriff erlaubt für Isolierung von Ressourcen gleichen Ursprungs: "https://registry.opentofu.org" auf "https://search.opentofu.org". search.opentofu.org
TypeError: Object.groupBy is not a function
    sy https://search.opentofu.org/assets/index-CigypDqt.js:91
    Gg https://search.opentofu.org/assets/index-CigypDqt.js:38
    EC https://search.opentofu.org/assets/index-CigypDqt.js:40
    mC https://search.opentofu.org/assets/index-CigypDqt.js:40
    SI https://search.opentofu.org/assets/index-CigypDqt.js:40
    vf https://search.opentofu.org/assets/index-CigypDqt.js:40
    um https://search.opentofu.org/assets/index-CigypDqt.js:40
    fC https://search.opentofu.org/assets/index-CigypDqt.js:40
    w https://search.opentofu.org/assets/index-CigypDqt.js:25
    U https://search.opentofu.org/assets/index-CigypDqt.js:25
index-CigypDqt.js:40:161
React Router caught the following error during render TypeError: Object.groupBy is not a function
    sy https://search.opentofu.org/assets/index-CigypDqt.js:91
    Gg https://search.opentofu.org/assets/index-CigypDqt.js:38
    EC https://search.opentofu.org/assets/index-CigypDqt.js:40
    mC https://search.opentofu.org/assets/index-CigypDqt.js:40
    SI https://search.opentofu.org/assets/index-CigypDqt.js:40
    vf https://search.opentofu.org/assets/index-CigypDqt.js:40
    um https://search.opentofu.org/assets/index-CigypDqt.js:40
    fC https://search.opentofu.org/assets/index-CigypDqt.js:40
    w https://search.opentofu.org/assets/index-CigypDqt.js:25
    U https://search.opentofu.org/assets/index-CigypDqt.js:25
 
Object { componentStack: "\nwq@https://search.opentofu.org/assets/index-CigypDqt.js:138:5254\nz4@https://search.opentofu.org/assets/index-CigypDqt.js:60:2996\nV4@https://search.opentofu.org/assets/index-CigypDqt.js:60:3778\nV4@https://search.opentofu.org/assets/index-CigypDqt.js:60:3778\nV4@https://search.opentofu.org/assets/index-CigypDqt.js:60:3778\nz4@https://search.opentofu.org/assets/index-CigypDqt.js:60:2996\ng5@https://search.opentofu.org/assets/index-CigypDqt.js:69:5368\nZ4@https://search.opentofu.org/assets/index-CigypDqt.js:60:7514\np5@https://search.opentofu.org/assets/index-CigypDqt.js:69:2589\nz5@https://search.opentofu.org/assets/index-CigypDqt.js:69:44398\nba@https://search.opentofu.org/assets/index-CigypDqt.js:69:57562" }
index-CigypDqt.js:60:3449

**Comment by Yantrio** [comment]
Thanks for reporting this, we're actively investigating this area.
