### ISSUE TITLE
Spacing between text and inline code block

### ISSUE THREAD

**Issue by abstractionfactory** [opentofu/registry-ui#200]
### URL of the page that's broken

N/A

### Screenshot

![image](https://github.com/user-attachments/assets/77451813-6459-4098-b2da-394db2d17eea)

### OS, browser version, installed extensions

Firefox, Windows

### Additional information

When parsing text next to code, there seems to be some spacing missing (see screenshot)

**Comment by damianstasik** [comment]
@abstractionfactory this should be fixed by #183, could you please confirm whether that's the case?

**Comment by damianstasik** [comment]
This should be now working as expected, here's preview from the `registry-docs` branch:
![Screenshot 2024-09-10 at 13 28 21](https://github.com/user-attachments/assets/62e2888a-bcb9-4f3f-a322-fc227b8cca92)
