### ISSUE TITLE
No access to the content of some versions of providers

### ISSUE THREAD

**Issue by nikpivkin** [opentofu/registry-ui#43]
Version `0.0.2` of the `env0/env0` provider is in the sidebar on the right, but the content of this version is not available.

https://search.opentofu.org/provider/env0/env0/v0.0.2

<img width="1036" alt="image" src="https://github.com/user-attachments/assets/9dbaf04e-d3c2-4f08-804a-d5e25d5d5970">

**Comment by nikpivkin** [comment]
It may be related, but I'm not sure https://github.com/opentofu/registry-ui/issues/36

**Comment by damianstasik** [comment]
The UI now handles the missing MD file, but we still display such versions in the sidebar.

@abstractionfactory should we filter such providers from the API?

**Comment by Yantrio** [comment]
This is now resolved. We are correctly only displaying valid versions in our sidebar now.
